/**
 * Kickoff prompt for the daily CLOUD-half recruiting sweep.
 *
 * Split out of recruiting-sweep.ts on 2026-09-09 so the prompt can be asserted
 * in a unit test without importing the cron handler (which pulls in
 * workforce-hub and recruiting-report). The underscore prefix keeps Vercel from
 * treating this as a route, same convention as api/_oauth.ts.
 *
 * WHY THE TEST EXISTS: the VideoAsk nudge tools shipped 2026-08-20 (PR #66),
 * which deliberately deferred wiring them into this prompt so the next morning's
 * run would not call tools that were not deployed yet. The follow-up never
 * landed. For three weeks the cloud half invited candidates and then never
 * followed up with a single one — live tools, unreachable. Keeping the prompt in
 * its own module with a test guarding the nudge stage is how that stops
 * happening silently.
 */

export const DEFAULT_PROMPT = [
  "Run your daily CLOUD-half recruiting invite sweep for today (America/Chicago).",
  "Follow your system prompt exactly. In short: (1) get_recruiting_state — read",
  "last_run_cloud and last_run_browser; your sweep window starts at last_run_cloud",
  "(minimum 2 days back; if the gap is larger, the window widens automatically —",
  "say so in your report). (2) Sweep every cloud channel via get_new_applicants:",
  "website, wix, wizehire, indeed, true_analysis, hazelequity. THEN also call",
  "get_forwarded_resumes with the same since_iso — a separate tool, added 2026-09-09,",
  "for resumes emailed straight to Cranbrook and forwarded on by the on-site manager",
  "or Yuliana. Five arrived that way in one afternoon and none could be invited,",
  "because true_analysis only exposes a 300-character snippet and these bodies open",
  "with the property's signature block. It returns parsed applicants — treat them",
  "exactly like website leads and invite them in step 3; role defaults to Assistant",
  "Community Manager since these emails never name one. Anything it returns under",
  "`unparsed` had no readable sender — list those under NEEDS YOU by subject so Mo",
  "can open them by hand. If hazelequity",
  "returns swept:false, report it as UNSWEPT, never as zero applicants. The",
  "indeed channel (added 2026-08-18) returns individual application emails with",
  "full body — extract each candidate's name, email (relay …@indeedemail.com",
  "addresses are valid), and role yourself; a hit with no extractable email is",
  "skipped quietly (Indeed bundles applications at volume; those applicants were",
  "already invited natively by the posting's own Indeed automation — this is NOT",
  "a misconfiguration, never raise it). The indeed channel also returns",
  "`candidate_replies` — candidates writing back inside their Indeed thread",
  '("completed the video", "is the role still open", "please call me"). NEVER',
  "invite a reply (Indeed rejects it and the tool refuses); instead put them",
  "under NEEDS YOU as 'Indeed replies waiting (<n>): Name (Role) — first words',",
  "up to 3 names then '+n more', so Mo answers them in Indeed messaging. Never",
  "invite from `digests` (volume context only), and ignore digest copies",
  "appearing in true_analysis.",
  "The Mac browser half is LinkedIn-ONLY now: only LinkedIn items go to",
  "carry_forward for it. (3) For each",
  "applicant, call send_recruiting_invite — dedup, the do-not-contact",
  "list, and the daily cap are enforced inside the tool; if it refuses, accept",
  "the refusal and log why. Since 2026-08-18 ALL roles are invitable (EA,",
  "Virtual Sales, Virtual PM, VLS, Maintenance included — the tool maps each",
  "role to its questionnaire; this supersedes any out-of-scope list in your",
  "system prompt). If a role cannot be mapped the tool refuses — list that",
  "applicant BY NAME + role in your report for Mo. Wix hits are often",
  "property-owner sales leads, not applicants — only invite real job applicants.",
  "(4) Watchdog: if last_run_browser is more than 3 days old, send_watchdog_alert",
  "so Mo knows LinkedIn/Indeed are going stale. (5) update_recruiting_state:",
  "set last_run_cloud to now — the CURRENT actual UTC time as full ISO, never a",
  "rounded or future time — and carry_forward to anything unfinished.",
  "(6) TestGorilla stage (added 2026-08-18, Mo's ask): read testgorilla_boundary",
  "from state — its value is an object; the timestamp is its `boundary` field.",
  "If the key is MISSING or the boundary unparsable, send NOTHING for this",
  "stage and flag it under Needs-you. Otherwise call get_videoask_completers",
  "with since_iso = that boundary (default question = Virtual PM final",
  "screening question), then send_testgorilla_invite for each completer,",
  "OLDEST first — dedup, cap, and do-not-contact are enforced in the tool;",
  "accept refusals. NEVER skip a completer because their name is missing or is",
  "an email address rather than a name — people mistype the VideoAsk name",
  "field. Pass what you have and the greeting falls back to 'Hi there'; they",
  "finished the screening, so they get the assessment. Afterwards update testgorilla_boundary keeping the object",
  "shape: { boundary: <newest completed_at you actually PROCESSED (attempted",
  "or dedup-refused)>, last_invited: <that person's name> }. If the",
  "daily cap stops you, do NOT advance the boundary past the last processed",
  "completer, and note the remaining backlog count in your report headline.",
  "(7) NUDGE PASS — Mo's standing ruling of 2026-09-09: one nudge at 72 hours,",
  "never a second, never to someone who wrote back. Do not skip this stage. The",
  "tools for it shipped 2026-08-20 but were never wired into this kickoff, so",
  "between 2026-08-20 and 2026-09-09 every candidate this sweep invited was then",
  "left alone forever — follow-through, not supply, is the bottleneck in this",
  "funnel. Call get_videoask_pending with days_since_invite 3 (that is Mo's 72",
  "hours) — it returns people WE invited who never engaged with the questionnaire",
  "and have never been nudged. Then call send_videoask_reminder for each one.",
  "ONE nudge per candidate ever, the daily cap, the do-not-contact list, the",
  "proof-of-invite check and a fail-CLOSED VideoAsk check are all enforced inside",
  "the tool — accept every refusal as final and never retry it.",
  "HARD EXCLUSION: anyone who has WRITTEN BACK is off limits. Cross-check the",
  "`candidate_replies` you collected from the indeed channel in step 2, plus any",
  "reply you saw in true_analysis, and do NOT nudge those people even if they",
  "appear in the pending list. A replier is a live conversation and belongs to",
  "Mo, not to an automated reminder — they are already surfaced by the",
  "Indeed-replies line under NEEDS YOU.",
  "COVERAGE CAVEAT you must respect when you write the report: the pending roster",
  "is built from OUR OWN sent invite emails, so LinkedIn-invited candidates and",
  "Indeed-native-bundle applicants are NOT in it. Never say or imply the whole",
  "pipeline was nudged. If the daily cap stops you, say how many are still",
  "waiting in the headline.",
  "(8) report_recruiting_run with a one-line summary AND the `report` field.",
  "FORMAT (Mo's rule, 2026-08-18 — headline + action items ONLY, never a log):",
  "the `report` first line is ONE plain-English sentence with the outcome and",
  "counts, e.g. '10 invites sent (8 EA, 2 Maint Coord); all 5 channels swept;",
  "5 duplicates auto-blocked'. Then ONLY if something needs Mo, add a line that",
  "is exactly 'NEEDS YOU:' on its own — that literal marker is what the tool",
  "keys off to pull your reason out; anything above it is discarded — followed",
  "by 1-3 short '- ' bullets. Needs-you items are:",
  "Indeed candidate replies waiting (names + roles, see above),",
  "unmappable-role applicants (by name + role), any UNSWEPT channel, watchdog",
  "fired / last_run_browser more than 2 days old (say new Indeed/LinkedIn",
  "applicants are waiting on his Mac), send errors, or anything else requiring",
  "his action. A quiet day = the single headline line and NOTHING else. Never",
  "list individual invitees, dedup refusals, per-channel zero counts, or",
  "routine carry-forward — that detail lives in state and the run row, not in",
  "Mo's message.",
  "This fire may be a RETRY — that is normal; the send tool's per-day log makes",
  "duplicate emails impossible, so simply continue any unfinished work. BUT if",
  "last_run_cloud is less than 2 hours old, the first fire already completed:",
  "do NOT re-sweep — call report_recruiting_run with status ok, summary",
  "'retry no-op — first run already completed', and NO report field (so Mo is",
  "not messaged twice), then stop.",
].join(" ");
